#  Day 07 - Product & Customer Analysis

##  Objective

Analyze products and customers to identify top performers and products that generate losses.

In [1]:
import pandas as pd

df = pd.read_excel("C:/Data Projects/Ecommerce_Sales_Analysis/Data/Superstore.xlsx")

## Top 10 Products by Sales

In [2]:
top_sales_products = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_sales_products

Product Name
Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection            23155.6200
It's Hot Message Books with Stickers, 2 3/4" x 5"                                    17834.8820
Easy-staple paper                                                                    14885.7380
Aastra 57i VoIP phone                                                                14404.6380
Tenex B1-RE Series Chair Mats for Low Pile Carpets                                   13563.4630
Ultra Door Pull Handle                                                               12515.4660
Acme Hot Forged Carbon Steel Scissors with Nickel-Plated Handles, 3 7/8" Cut, 8"L    11990.8380
Panasonic KX - TS880B Telephone                                                      11503.9740
Staple envelope                                                                      10727.0965
Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive                                  10085.7000
Name: Sales, dtype: float64

## Top 10 Products by Profit

In [3]:
top_profit_products = (
    df.groupby("Product Name")["Profit"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_profit_products

Product Name
Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection            8176.5065
It's Hot Message Books with Stickers, 2 3/4" x 5"                                    6759.1212
Tenex B1-RE Series Chair Mats for Low Pile Carpets                                   5328.6234
Aastra 57i VoIP phone                                                                4992.4032
Ultra Door Pull Handle                                                               4981.0747
Panasonic KX - TS880B Telephone                                                      4249.2448
Logitech G430 Surround Sound Gaming Headset with Dolby 7.1 Technology                3205.9575
Acme Hot Forged Carbon Steel Scissors with Nickel-Plated Handles, 3 7/8" Cut, 8"L    3201.9413
Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive                                  2948.8395
Panasonic KX TS208W Corded phone                                                     2649.6849
Name: Profit, dtype: float64

## Bottom 10 Products by Profit

In [6]:
bottom_profit_products = (
    df.groupby("Product Name")["Profit"]
      .sum()
      .sort_values()
      .head(10)
)

bottom_profit_products

Product Name
Bush Somerset Collection Bookcase                                  -6388.4002
Bretford CR4500 Series Slim Rectangular Table                      -4294.3417
Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back        -3836.3923
Self-Adhesive Address Labels for Typewriters by Universal          -3661.7805
Eldon Fold 'N Roll Cart System                                     -2880.7693
Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood   -2591.5417
Newell 322                                                         -2219.7895
DXL Angle-View Binders with Locking Rings by Samsill               -1863.7763
Mitel 5320 IP Phone VoIP phone                                     -1796.4036
Chromcraft Rectangular Conference Tables                           -1535.9158
Name: Profit, dtype: float64

## Top 10 Customers by Sales

In [7]:
top_customers = (
    df.groupby("Customer Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_customers

Customer Name
Dave Brooks         43374.790
Anne Pryor          41113.110
Chris Cortes        24709.552
Ken Dana            23182.309
Ryan Crowe          21482.016
Ruben Ausman        20598.722
Helen Wasserman     19715.906
Hallie Redmond      18235.384
Dianna Vittorini    18093.912
Darren Budd         17109.478
Name: Sales, dtype: float64

## Top Customers With High Sales and Profit

In [8]:
customer_analysis = (
    df.groupby("Customer Name")
      .agg({
          "Sales": "sum",
          "Profit": "sum"
      })
      .sort_values(by="Sales", ascending=False)
)

customer_analysis.head(10)

                      Sales      Profit
Customer Name
Dave Brooks       43374.790  16492.9628
Anne Pryor        41113.110  13562.5465
Chris Cortes      24709.552   8682.6172
Ken Dana          23182.309   5274.4938
Ryan Crowe        21482.016   5111.9979
Ruben Ausman      20598.722   6686.9597
Helen Wasserman   19715.906   4719.9772
Hallie Redmond    18235.384   3916.4405
Dianna Vittorini  18093.912   5015.7757
Darren Budd       17109.478   4224.9739

In [9]:
customer_analysis["Profit Margin %"] = (
    customer_analysis["Profit"] / customer_analysis["Sales"]
) * 100

customer_analysis.sort_values(by="Sales", ascending=False).head(10)

                      Sales      Profit  Profit Margin %
Customer Name
Dave Brooks       43374.790  16492.9628        38.024306
Anne Pryor        41113.110  13562.5465        32.988374
Chris Cortes      24709.552   8682.6172        35.138707
Ken Dana          23182.309   5274.4938        22.752237
Ryan Crowe        21482.016   5111.9979        23.796639
Ruben Ausman      20598.722   6686.9597        32.462983
Helen Wasserman   19715.906   4719.9772        23.939946
Hallie Redmond    18235.384   3916.4405        21.477148
Dianna Vittorini  18093.912   5015.7757        27.720792
Darren Budd       17109.478   4224.9739        24.693763

## Top Customers With High Profit Margin

In [10]:
customer_analysis.sort_values(
    by="Profit Margin %",
    ascending=False
).head(10)

                      Sales      Profit  Profit Margin %
Customer Name
Tom Boeckenhauer  11366.354   4741.5637        41.715784
Dave Brooks       43374.790  16492.9628        38.024306
Chris Cortes      24709.552   8682.6172        35.138707
Anne Pryor        41113.110  13562.5465        32.988374
Ruben Ausman      20598.722   6686.9597        32.462983
Shaun Weien        8127.130   2405.0435        29.592778
Maris LaWare       9962.158   2926.9988        29.381172
Richard Bierner   16098.828   4565.0688        28.356529
Corinna Mitchell   9042.564   2521.8745        27.888932
Dianna Vittorini  18093.912   5015.7757        27.720792

## Tasks Completed

- Identified the top 10 products by sales.
- Identified the top 10 products by profit.
- Identified the bottom 10 products by profit.
- Identified the top 10 customers by sales.
- Identified the top 10 customers by profit.

---

## Skills Learned

- Using `head()` to retrieve top records.
- Ranking products and customers using `groupby()` and `sort_values()`.
- Identifying high-performing and low-performing products.
- Supporting business decisions using data analysis.

---

## Business Recommendations

- Reward high-profit customers through loyalty programs.
- Review pricing and discount strategies for customers with high sales but low profit margins.
- Focus marketing efforts on customers who generate both high sales and strong profitability.

---

## Conclusion

The analysis highlights the company's best-performing products and customers while identifying products that negatively impact profitability. These insights can help improve inventory management, pricing strategies, and customer relationship management.